#!/usr/bin/env perl
# A perl script to start on a given regexp and stop on another
# or a given line number and ending on another

use strict;
use warnings;

use Text::Abbrev;
use Data::Dumper;

my $last_mod_date='Wed, Jul 22, 2026';

my $version="1.2";

my $author="Dr. Steven Parker";
my $copyright="$last_mod_date. All rights reserved.";

my $name = $0; $name =~ s'.*/''; # remove path--like basename
my $usage  = "usage:\n$name\n\t";
$usage .= "[ ( -?      | -help  | -debug | -usage ) ]\n\t";
$usage .= "[ ( -on     | -begin | -start ) start_regexp ]\n\t";
$usage .= "[ ( -off    | -end   | -stop  ) stop_regexp ]\n\t";
$usage .= "[ ( -regexp | -find  | -grep  ) regexp ]\n\t";
$usage .= "[ -lead N -linger M  | -context N ]\n\t";
$usage .= "[  N..M     |  N..   |  ..M  |  N  ]\n\t";
$usage .= "[ -number ]\n\t";
$usage .= "[ [ -file ] file1 file2 .. ]";

my $plan = initialize_plan();

parse_arguments($plan, @ARGV);
validate_plan($plan);
push @{$plan->{files}}, '-' unless @{$plan->{files}};
print Dumper($plan) if ($plan->{debug});
my $stats = execute_plan($plan);

exit 2 if $stats->{errors};
exit($stats->{lines_printed} ? 0 : 1);

sub initialize_plan {
  return {
    debug          => 0,
    explanations   => [],
    files          => [],
    lead           => 0,
    linger         => 0,
    print_stops    => 1,
    ranges         => [],
    start_lines    => {},
    start_printing => 0,
    stop_lines     => {},
  };
}

sub execute_plan {
  my $plan = shift;
  my $stats = {
    ends_matched   => 0,
    errors         => 0,
    files_processed => 0,
    lines_printed  => 0,
    lines_read     => 0,
    lines_skipped  => 0,
    starts_matched => 0,
  };

  foreach my $file (@{$plan->{files}}) {
    my $state = {
      active_rule => undef,
      filename    => $file,
      lead_buffer => [],
      line_number => 0,
      linger_left => 0,
      printing    => $plan->{start_printing},
    };

    my $filehandle;
    if ($file eq '-') {
      if (!open($filehandle, '<-')) {
        warn "Cannot read from STDIN: $!\n";
        $stats->{errors}++;
        next;
      }
    } else {
      if (!open($filehandle, '<', $file)) {
        warn "Cannot read from '$file': $!\n";
        $stats->{errors}++;
        next;
      }
    }
    $stats->{files_processed}++;

    while (my $line = <$filehandle>) {
      $state->{line_number}++;
      $stats->{lines_read}++;

      my $was_printing = $state->{printing};
      my $start_match =
        $plan->{start_lines}{$state->{line_number}} ||
        ($plan->{start_regexp} && $line =~ $plan->{start_regexp});
      my $end_match =
        $plan->{stop_lines}{$state->{line_number}} ||
        ($plan->{stop_regexp} && $line =~ $plan->{stop_regexp});
      my $single_match = $plan->{regexp} && $line =~ $plan->{regexp};
      my $active_end = ($was_printing || $start_match) && $end_match;
      my $within_linger = $state->{linger_left} > 0;

      $stats->{starts_matched}++ if $start_match;
      $stats->{ends_matched}++ if $active_end;

      if ($start_match || $single_match) {
        while (@{$state->{lead_buffer}}) {
          my $buffered = shift @{$state->{lead_buffer}};
          print_line(
            $plan,
            $state,
            $stats,
            $buffered->{text},
            $buffered->{number},
          );
        }
      }

      if ($was_printing || $start_match || $single_match || $within_linger) {
        print_line($plan, $state, $stats, $line);
      } else {
        if ($plan->{lead}) {
          push @{$state->{lead_buffer}}, {
            number => $state->{line_number},
            text   => $line,
          };
          if (@{$state->{lead_buffer}} > $plan->{lead}) {
            shift @{$state->{lead_buffer}};
            $stats->{lines_skipped}++;
          }
        } else {
          $stats->{lines_skipped}++;
        }
      }

      $state->{printing} =
        $was_printing ? !$end_match : ($start_match && !$end_match);

      $state->{linger_left}-- if $within_linger;
      if ($single_match || $active_end) {
        $state->{linger_left} = $plan->{linger}
          if $plan->{linger} > $state->{linger_left};
      }
    }

    $stats->{lines_skipped} += @{$state->{lead_buffer}};
    if (!close($filehandle)) {
      warn "Cannot close '$file': $!\n";
      $stats->{errors}++;
    }
  }

  return $stats;
}

sub print_line {
  my ($plan, $state, $stats, $line, $line_number) = @_;
  $line_number //= $state->{line_number};
  $stats->{lines_printed}++;
  printf "%5d ", $line_number if ($plan->{number});
  print $line;
}

sub parse_arguments {
  my $plan = shift;
  my (@start_regexps, @stop_regexps, @regexps);
  my @args=('?','help','debug','usage');
  my @help=('print this message','print this message','set debugging flag','print short usage message');
  push(@args,'regexp','find','grep');
  push(@help,'regexp to identify a single-line print trigger, context may still apply',
         'regexp to identify a single-line print trigger, context may still apply',
         'regexp to identify a single-line print trigger, context may still apply',);
  push(@args,'on','start','begin','off','stop','end');
  push(@help,'regexp to trigger printing',
             'regexp to trigger printing',
             'regexp to trigger printing',
             'regexp to terminate printing',
             'regexp to terminate printing',
             'regexp to terminate printing');
  push(@args,'number');
  push(@help,'print line numbers before each printed line');
  push(@args,'lead','linger','context','file');
  push(@help,'# of lines to print before each print trigger',
             '# of lines to print after each terminate trigger',
             '# of lines to print before and after a trigger',
             'name of file to add to list of files to scan');
  grep(s/^([^-])/-$1/,@args);
  my $abbrev = abbrev @args;
  push(@args,'N','N..','..M','N..M');
  push(@help,"will print line N, ignoring start/stop regexp's",
             "start printing at line N, will continue until something terminates it",
             "will terminate printing at line M, ignoring start/stop regexp's",
             "will print all lines between N and M ignoring all all regexp triggers");
  for (my $arg=$[; $arg<=$#args; $arg++) {
    push ( @{$plan->{explanations}}, { arg => $args[$arg], explanation => $help[$arg] } );
  }
  while ( @ARGV >= 1 ) {
    if ( $abbrev->{$ARGV[0]} ) {                       # have a valid argument, find which one
      my $option = $abbrev->{$ARGV[0]};
      if ($option =~ /^-(?:regexp|find|grep|on|start|begin|off|stop|end|lead|linger|context|file)$/
          && @ARGV < 2) {
        usage_error("option '$ARGV[0]' requires a value");
      }
      if ( $abbrev->{$ARGV[0]} eq '-help' or  $abbrev->{$ARGV[0]} eq '-?' ) {
        help($plan);
        shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-usage' ) {
      	print "$usage\n";
      	exit 0;
      } elsif ( $abbrev->{$ARGV[0]} eq '-debug' ) {
        $plan->{debug} = 1;
        print "user specified debugging flag set\n";
        shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-number' ) {
        $plan->{number} = 1;
        print "user asked us to number the output lines\n" if ($plan->{debug});
        shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-regexp' or  $abbrev->{$ARGV[0]} eq '-find' or  $abbrev->{$ARGV[0]} eq '-grep' ) {
        push( @regexps, qq($ARGV[1]) );
        print "user specified '$ARGV[1]' as regexp to print\n" if ($plan->{debug});
        shift(@ARGV); shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-on' or  $abbrev->{$ARGV[0]} eq '-start' or  $abbrev->{$ARGV[0]} eq '-begin' ) {
        push( @start_regexps, qq($ARGV[1]) );
        print "user specified '$ARGV[1]' as regexp to be added to triggers to start printing\n" if ($plan->{debug});
        shift(@ARGV); shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-off' or  $abbrev->{$ARGV[0]} eq '-stop' or  $abbrev->{$ARGV[0]} eq '-end' ) {
        push( @stop_regexps, qq($ARGV[1]) );
        print "user specified '$ARGV[1]' as regexp to be added to triggers to stop printing\n" if ($plan->{debug});
        shift(@ARGV); shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-lead' ) {
        validate_nonnegative_integer('-lead', $ARGV[1]);
        $plan->{lead} = $ARGV[1];
        print "user specified '$ARGV[1]' as number of lines to print before each trigger regexp\n" if ($plan->{debug});
        shift(@ARGV); shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-linger' ) {
        validate_nonnegative_integer('-linger', $ARGV[1]);
        $plan->{linger} = $ARGV[1];
        print "user specified '$ARGV[1]' as number of lines to print after each terminate regexp\n" if ($plan->{debug});
        shift(@ARGV); shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-context' ) {
        validate_nonnegative_integer('-context', $ARGV[1]);
        $plan->{lead}   = $ARGV[1];
        $plan->{linger} = $ARGV[1];
        print "user specified '$ARGV[1]' as number of lines to print before each trigger regexp\n" if ($plan->{debug});
        print "and the same number of lines to print after each terminate regexp\n" if ($plan->{debug});
        shift(@ARGV); shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-file' ) {
        push(@{$plan->{files}},"$ARGV[1]") if $ARGV[1];
        print "add '$ARGV[1]' to list of files to scan\n" if ($plan->{debug});
        shift(@ARGV); shift(@ARGV);
      } else {
        print STDERR "'$ARGV[0]' doesn't appear to be implemented yet... strange?\n";
        exit;
      }
    } elsif ( $ARGV[0] =~ m'^-?(\d+)\.\.+(\d+)$' ) {                                    # N to M
      usage_error('line numbers must be greater than zero') if $1 == 0 || $2 == 0;
      usage_error("range start $1 is greater than range end $2") if $1 > $2;
      $plan->{start_lines}{$1}++;
      $plan->{stop_lines}{$2}++;
      print "user has requested printing of lines $1 to $2 inclusive\n" if ($plan->{debug});
      shift(@ARGV);
    } elsif ( $ARGV[0] =~ m'^-?(\d+)\.\.$' ) {                                          # N on
      usage_error('line numbers must be greater than zero') if $1 == 0;
      $plan->{start_lines}{$1}++;
      print "user has requested printing of lines starting at $1\n" if ($plan->{debug});
      shift(@ARGV);
    } elsif ( $ARGV[0] =~ m'^-?\.\.(\d+)$' ) {                                          #   to M
      usage_error('line numbers must be greater than zero') if $1 == 0;
      $plan->{start_printing} = 1;
      $plan->{stop_lines}{$1}++;
      push( @{$plan->{ranges}}, { start=>undef, end=>$1 } );
      print "user has requested printing of lines up to $1\n" if ($plan->{debug});
      shift(@ARGV);
    } elsif ( $ARGV[0] =~ m'^-?(\d+)$' ) {                                              # just print line N
      usage_error('line numbers must be greater than zero') if $1 == 0;
      $plan->{start_lines}{$1}++;
      $plan->{stop_lines}{$1}++;
      print "user has requested printing of line $1\n" if ($plan->{debug});
      shift(@ARGV);
    } elsif ( $ARGV[0] =~ m'^-?([^.]*)\.\.+([^.]*)$' ) {                                # START to STOP (at least one is not a number)
      my $front=$1;
      my $back=$2;
      if ($front eq '' and $back eq '') {
        usage_error("'..' is not a valid range");
      } elsif ($front eq '') { # ..SOMETHING (not a number)
        print " ..X '$front' '$back'\n" if ($plan->{debug});
        $plan->{start_printing} = 1;
        push( @stop_regexps, qq($back) );
      } elsif ($back eq '') { # SOMETHING.. (not a number)
        print "X..  '$front' '$back'\n" if ($plan->{debug});
        push( @start_regexps, qq($front) );
      } else {                # SOMETHING..SOMETHING_ELSE (at least one of which is not a number)
        print "X..Y '$front' '$back'\n" if ($plan->{debug});
        if ( $front=~/^\d+$/ ) {
          print "N..? '$front' '$back'\n" if ($plan->{debug});
          $plan->{start_lines}{$front}++;
        } else {
          print "X..? '$front' '$back'\n" if ($plan->{debug});
          push( @start_regexps, qq($front) );
        }
        if ( $back=~/^\d+$/ ) {
          print "?..N '$front' '$back'\n" if ($plan->{debug});
          $plan->{stop_lines}{$back}++;
        } else {
          print "?..X '$front' '$back'\n" if ($plan->{debug});
          push( @stop_regexps, qq($back) );
        }
      }
      shift(@ARGV);
    } else {
      usage_error("unknown option '$ARGV[0]'")
        if $ARGV[0] =~ /^-/ && $ARGV[0] ne '-';
      warn("$plan->{name}: Unknown option '$ARGV[0]'; assuming file to scan...\n") if ($plan->{debug});
      push(@{$plan->{files}},shift(@ARGV));
    }

    if (@start_regexps) {
      my $regexps_ored = join('|', @start_regexps);
      $plan->{start_regexp} = compile_regexp('start', $regexps_ored);
    }
    if (@stop_regexps) {
      my $regexps_ored = join('|', @stop_regexps);
      $plan->{stop_regexp} = compile_regexp('end', $regexps_ored);
    }
    if (@regexps) {
      my $regexps_ored = join('|', @regexps);
      $plan->{regexp} = compile_regexp('match', $regexps_ored);
    }
  }  # end while
  if ($plan->{debug}) {
    # print Dumper($abbrev);
    report_plan($plan);
  }
  # if (@$ranges) { @$plan->{ranges} = sort { ( $plan->{ranges}->[$a]{start} <=> $plan->{ranges}->[$b]{start} ) || ( $plan->{ranges}->[$a]{end} <=> $plan->{ranges}->[$b]{end} ) } @$ranges }
}  # end parse_args

sub validate_plan {
  my $plan = shift;
  validate_nonnegative_integer('-lead', $plan->{lead});
  validate_nonnegative_integer('-linger', $plan->{linger});
}

sub validate_nonnegative_integer {
  my ($option, $value) = @_;
  usage_error("$option requires a non-negative integer")
    unless defined $value && $value =~ /^\d+$/;
}

sub compile_regexp {
  my ($kind, $source) = @_;
  my $regexp = eval { qr/$source/ };
  if (!$regexp || $@) {
    my $error = $@ || 'unknown regular-expression error';
    $error =~ s/\s+at\s+\Q$0\E\s+line\s+\d+.*//s;
    chomp $error;
    usage_error("invalid $kind regular expression '$source': $error");
  }
  return $regexp;
}

sub usage_error {
  my $message = shift;
  warn "onoff: $message\n";
  exit 2;
}

sub help {
  my ($plan,@args) = @_;
  select(STDOUT); $|=1; $\=''; 
  if (@{$plan->{explanations}}) {
    foreach my $explanation ( @{$plan->{explanations}} ) {
      printf "%-16s\t%s\n", $explanation->{arg}, $explanation->{explanation};
    }
  } else {
    for (my $arg=$[; $arg<=$#args; $arg++) {
      print "$args[$arg]\t";
    }
    print "\n";
  }
  exit 0;
}

sub report_plan {
  my $plan = shift;
  print "singles\n";
  print "set regexp to '$plan->{regexp}'\n" if ($plan->{regexp});
  print "starts\n";
  print "set start  to '$plan->{start_regexp}'\n" if ($plan->{start_regexp});
  print "set starts at: " . join(', ', keys %{$plan->{start_lines}}) . "\n" if ($plan->{start_lines});
  print "\nstops\n";
  print "set stop   to '$plan->{stop_regexp}'\n" if ($plan->{stop_regexp});
  print "set stops  at: " . join(', ', keys %{$plan->{stop_lines}}) . "\n" if ($plan->{stop_lines});
  print "\nfiles?\n";
  print "$_\n" foreach (@{$plan->{files}});
  print "lead, linger: $plan->{lead}, $plan->{linger}\n";
  print "=" x 40 . "\n";
}

__END__
