#!/usr/bin/env perl
# A perl script to start on a given regexp and stop on another
# or a given line number and ending on another

use strict;
use warnings;

use Text::Abbrev;
use Data::Dumper;

my $last_mod_date='Wed, Jun 21, 2023';

my $version="1.2";

my $author="Dr. Steven Parker";
my $copyright="$last_mod_date. All rights reserved.";

my $name = $0; $name =~ s'.*/''; # remove path--like basename
my $usage  = "usage:\n$name\n\t";
$usage .= "[ ( -?      | -help  | -debug | -usage ) ]\n\t";
$usage .= "[ ( -on     | -begin | -start ) start_regexp ]\n\t";
$usage .= "[ ( -off    | -end   | -stop  ) stop_regexp ]\n\t";
$usage .= "[ ( -regexp | -find  | -grep  ) regexp ]\n\t";
$usage .= "[ -lead N -linger M  | -context N ]\n\t";
$usage .= "[  N..M     |  N..   |  ..M  |  N  ]\n\t";
$usage .= "[ -number ]\n\t";
$usage .= "[ [ -file ] file1 file2 .. ]";

my $plan = initialize_plan();

parse_arguments($plan, @ARGV);
print Dumper($plan) if ($plan->{debug});
execute_plan($plan);

exit 0;

sub initialize_plan {
  return {
    debug          => 0,
    explanations   => [],
    files          => [],
    lead           => 0,
    linger         => 0,
    print_stops    => 1,
    ranges         => [],
    start_lines    => {},
    start_printing => 0,
    stop_lines     => {},
  };
}

sub execute_plan {
  my $plan = shift;
  foreach my $file (@{$plan->{files}}) {
    my $state = {
      active_rule => undef,
      filename    => $file,
      lead_buffer => [],
      line_number => 0,
      linger_left => 0,
      printing    => $plan->{start_printing},
    };
    my $stats = {
      ends_matched   => 0,
      lines_printed  => 0,
      lines_read     => 0,
      lines_skipped  => 0,
      starts_matched => 0,
    };

    my $filehandle;
    if ($file eq '-') {
      open($filehandle, '<-') or die("Cannot read from STDIN: $!\n");
    } else {
      open($filehandle, '<', $file) or die("Cannot read from '$file': $!\n");
    }

    while (my $line = <$filehandle>) {
      $state->{line_number}++;
      $stats->{lines_read}++;
      if ($state->{printing}) {  # --- PRINTING ---
        if ($plan->{stop_lines}{$state->{line_number}} or
            ($plan->{stop_regexp} and $line =~ $plan->{stop_regexp})) {
          $stats->{ends_matched}++;
          if ($plan->{print_stops}) {
            print_line($plan, $state, $stats, $line);
            $state->{printing} = 0;
          }
          $state->{linger_left} = $plan->{linger};
          if ($state->{linger_left}) {
            print "Lingering printing active, $state->{linger_left}\n" if ($plan->{debug});
            while ($state->{linger_left} and $line = <$filehandle>) {
              $state->{line_number}++;
              $stats->{lines_read}++;
              print "$state->{linger_left} " if ($plan->{debug});
              print_line($plan, $state, $stats, $line);
              $state->{linger_left}--;
            }
          }
        } else {
          print_line($plan, $state, $stats, $line);
        }
      } else {  # --- NOT PRINTING ---
        if ($plan->{start_lines}{$state->{line_number}} or
            ($plan->{start_regexp} and $line =~ $plan->{start_regexp})) {
          $stats->{starts_matched}++;
          if ($plan->{lead}) {
            print "Leading printing active: $plan->{lead}\n" if ($plan->{debug});
            while (@{$state->{lead_buffer}}) {
              my $remembered_line = shift @{$state->{lead_buffer}};
              my $remembered_number = $state->{line_number} - @{$state->{lead_buffer}} - 1;
              print_line($plan, $state, $stats, $remembered_line, $remembered_number);
            }
          }
          print_line($plan, $state, $stats, $line);
          if (($plan->{stop_regexp} and $line =~ $plan->{stop_regexp}) or
              $plan->{stop_lines}{$state->{line_number}}) {
            $state->{linger_left} = $plan->{linger};
            if ($state->{linger_left}) {
              print "lingering printing active, $state->{linger_left}\n" if ($plan->{debug});
              while ($state->{linger_left} and $line = <$filehandle>) {
                $state->{line_number}++;
                $stats->{lines_read}++;
                print "$state->{linger_left} " if ($plan->{debug});
                print_line($plan, $state, $stats, $line);
                $state->{linger_left}--;
              }
            }
          } else {
            $state->{printing} = 1;
          }
        } elsif ($plan->{regexp} and $line =~ $plan->{regexp}) {
          if ($plan->{lead}) {
            print "leading printing active: $plan->{lead}\n" if ($plan->{debug});
            while (@{$state->{lead_buffer}}) {
              my $remembered_line = shift @{$state->{lead_buffer}};
              my $remembered_number = $state->{line_number} - @{$state->{lead_buffer}} - 1;
              print_line($plan, $state, $stats, $remembered_line, $remembered_number);
            }
          }
          print_line($plan, $state, $stats, $line);
          $state->{linger_left} = $plan->{linger};
          if ($state->{linger_left}) {
            print "Lingering Printing active, $state->{linger_left}\n" if ($plan->{debug});
            while ($state->{linger_left} and $line = <$filehandle>) {
              $state->{line_number}++;
              $stats->{lines_read}++;
              print "$state->{linger_left} " if ($plan->{debug});
              print_line($plan, $state, $stats, $line);
              $state->{linger_left}--;
            }
          }
        } else {
          if ($plan->{lead}) {
            push @{$state->{lead_buffer}}, $line;
            if (@{$state->{lead_buffer}} > $plan->{lead}) {
              shift @{$state->{lead_buffer}};
            }
          }
          $stats->{lines_skipped}++;
        }
      }
    }
    close($filehandle) or die("Cannot close '$file': $!\n");
  }
}

sub print_line {
  my ($plan, $state, $stats, $line, $line_number) = @_;
  $line_number //= $state->{line_number};
  $stats->{lines_printed}++;
  printf "%5d ", $line_number if ($plan->{number});
  print $line;
}

sub parse_arguments {
  my $plan = shift;
  my (@start_regexps, @stop_regexps, @regexps);
  my @args=('?','help','debug','usage');
  my @help=('print this message','print this message','set debugging flag','print short usage message');
  push(@args,'regexp','find','grep');
  push(@help,'regexp to identify a single-line print trigger, context may still apply',
         'regexp to identify a single-line print trigger, context may still apply',
         'regexp to identify a single-line print trigger, context may still apply',);
  push(@args,'on','start','begin','off','stop','end');
  push(@help,'regexp to trigger printing',
             'regexp to trigger printing',
             'regexp to trigger printing',
             'regexp to terminate printing',
             'regexp to terminate printing',
             'regexp to terminate printing');
  push(@args,'number');
  push(@help,'print line numbers before each printed line');
  push(@args,'lead','linger','context','file');
  push(@help,'# of lines to print before each print trigger',
             '# of lines to print after each terminate trigger',
             '# of lines to print before and after a trigger',
             'name of file to add to list of files to scan');
  grep(s/^([^-])/-$1/,@args);
  my $abbrev = abbrev @args;
  push(@args,'N','N..','..M','N..M');
  push(@help,"will print line N, ignoring start/stop regexp's",
             "start printing at line N, will continue until something terminates it",
             "will terminate printing at line M, ignoring start/stop regexp's",
             "will print all lines between N and M ignoring all all regexp triggers");
  for (my $arg=$[; $arg<=$#args; $arg++) {
    push ( @{$plan->{explanations}}, { arg => $args[$arg], explanation => $help[$arg] } );
  }
  while ( @ARGV >= 1 ) {
    if ( $abbrev->{$ARGV[0]} ) {                       # have a valid argument, find which one
      if ( $abbrev->{$ARGV[0]} eq '-help' or  $abbrev->{$ARGV[0]} eq '-?' ) {
        help($plan);
        shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-usage' ) {
      	print "$usage\n";
      	exit 0;
      } elsif ( $abbrev->{$ARGV[0]} eq '-debug' ) {
        $plan->{debug} = 1;
        print "user specified debugging flag set\n";
        shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-number' ) {
        $plan->{number} = 1;
        print "user asked us to number the output lines\n" if ($plan->{debug});
        shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-regexp' or  $abbrev->{$ARGV[0]} eq '-find' or  $abbrev->{$ARGV[0]} eq '-grep' ) {
        push( @regexps, qq($ARGV[1]) );
        print "user specified '$ARGV[1]' as regexp to print\n" if ($plan->{debug});
        shift(@ARGV); shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-on' or  $abbrev->{$ARGV[0]} eq '-start' or  $abbrev->{$ARGV[0]} eq '-begin' ) {
        push( @start_regexps, qq($ARGV[1]) );
        print "user specified '$ARGV[1]' as regexp to be added to triggers to start printing\n" if ($plan->{debug});
        shift(@ARGV); shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-off' or  $abbrev->{$ARGV[0]} eq '-stop' or  $abbrev->{$ARGV[0]} eq '-end' ) {
        push( @stop_regexps, qq($ARGV[1]) );
        print "user specified '$ARGV[1]' as regexp to be added to triggers to stop printing\n" if ($plan->{debug});
        shift(@ARGV); shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-lead' ) {
        $plan->{lead} = $ARGV[1];
        print "user specified '$ARGV[1]' as number of lines to print before each trigger regexp\n" if ($plan->{debug});
        shift(@ARGV); shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-linger' ) {
        $plan->{linger} = $ARGV[1];
        print "user specified '$ARGV[1]' as number of lines to print after each terminate regexp\n" if ($plan->{debug});
        shift(@ARGV); shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-context' ) {
        $plan->{lead}   = $ARGV[1];
        $plan->{linger} = $ARGV[1];
        print "user specified '$ARGV[1]' as number of lines to print before each trigger regexp\n" if ($plan->{debug});
        print "and the same number of lines to print after each terminate regexp\n" if ($plan->{debug});
        shift(@ARGV); shift(@ARGV);
      } elsif ( $abbrev->{$ARGV[0]} eq '-file' ) {
        push(@{$plan->{files}},"$ARGV[1]") if $ARGV[1];
        print "add '$ARGV[1]' to list of files to scan\n" if ($plan->{debug});
        shift(@ARGV); shift(@ARGV);
      } else {
        print STDERR "'$ARGV[0]' doesn't appear to be implemented yet... strange?\n";
        exit;
      }
    } elsif ( $ARGV[0] =~ m'^-?(\d+)\.\.+(\d+)$' ) {                                    # N to M
      $plan->{start_lines}{$1}++;
      $plan->{stop_lines}{$2}++;
      print "user has requested printing of lines $1 to $2 inclusive\n" if ($plan->{debug});
      shift(@ARGV);
    } elsif ( $ARGV[0] =~ m'^-?(\d+)\.\.$' ) {                                          # N on
      $plan->{start_lines}{$1}++;
      print "user has requested printing of lines starting at $1\n" if ($plan->{debug});
      shift(@ARGV);
    } elsif ( $ARGV[0] =~ m'^-?\.\.(\d+)$' ) {                                          #   to M
      $plan->{start_printing} = 1;
      $plan->{stop_lines}{$1}++;
      push( @{$plan->{ranges}}, { start=>undef, end=>$1 } );
      print "user has requested printing of lines up to $1\n" if ($plan->{debug});
      shift(@ARGV);
    } elsif ( $ARGV[0] =~ m'^-?(\d+)$' ) {                                              # just print line N
      $plan->{start_lines}{$1}++;
      $plan->{stop_lines}{$1}++;
      print "user has requested printing of line $1\n" if ($plan->{debug});
      shift(@ARGV);
    } elsif ( $ARGV[0] =~ m'^-?([^.]*)\.\.+([^.]*)$' ) {                                # START to STOP (at least one is not a number)
      my $front=$1;
      my $back=$2;
      if ($front eq '' and $back eq '') {
        print "'..' is not a valid option.\n";
      } elsif ($front eq '') { # ..SOMETHING (not a number)
        print " ..X '$front' '$back'\n" if ($plan->{debug});
        $plan->{start_printing} = 1;
        push( @stop_regexps, qq($back) );
      } elsif ($back eq '') { # SOMETHING.. (not a number)
        print "X..  '$front' '$back'\n" if ($plan->{debug});
        push( @start_regexps, qq($front) );
      } else {                # SOMETHING..SOMETHING_ELSE (at least one of which is not a number)
        print "X..Y '$front' '$back'\n" if ($plan->{debug});
        if ( $front=~/^\d+$/ ) {
          print "N..? '$front' '$back'\n" if ($plan->{debug});
          $plan->{start_lines}{$front}++;
        } else {
          print "X..? '$front' '$back'\n" if ($plan->{debug});
          push( @start_regexps, qq($front) );
        }
        if ( $back=~/^\d+$/ ) {
          print "?..N '$front' '$back'\n" if ($plan->{debug});
          $plan->{stop_lines}{$back}++;
        } else {
          print "?..X '$front' '$back'\n" if ($plan->{debug});
          push( @stop_regexps, qq($back) );
        }
      }
      shift(@ARGV);
    } else {
      warn("$plan->{name}: Unknown option '$ARGV[0]'; assuming file to scan...\n") if ($plan->{debug});
      push(@{$plan->{files}},shift(@ARGV));
    }

    if (@start_regexps) {
      my $regexps_ored = join('|', @start_regexps);
      $plan->{start_regexp} = qr/$regexps_ored/;
    }
    if (@stop_regexps) {
      my $regexps_ored = join('|', @stop_regexps);
      $plan->{stop_regexp} = qr/$regexps_ored/;
    }
    if (@regexps) {
      my $regexps_ored = join('|', @regexps);
      $plan->{regexp} = qr/$regexps_ored/;
    }
  }  # end while
  if ($plan->{debug}) {
    # print Dumper($abbrev);
    report_plan($plan);
  }
  # if (@$ranges) { @$plan->{ranges} = sort { ( $plan->{ranges}->[$a]{start} <=> $plan->{ranges}->[$b]{start} ) || ( $plan->{ranges}->[$a]{end} <=> $plan->{ranges}->[$b]{end} ) } @$ranges }
}  # end parse_args

sub help {
  my ($plan,@args) = @_;
  select(STDOUT); $|=1; $\=''; 
  if (@{$plan->{explanations}}) {
    foreach my $explanation ( @{$plan->{explanations}} ) {
      printf "%-16s\t%s\n", $explanation->{arg}, $explanation->{explanation};
    }
  } else {
    for (my $arg=$[; $arg<=$#args; $arg++) {
      print "$args[$arg]\t";
    }
    print "\n";
  }
  exit 0;
}

sub report_plan {
  my $plan = shift;
  print "singles\n";
  print "set regexp to '$plan->{regexp}'\n" if ($plan->{regexp});
  print "starts\n";
  print "set start  to '$plan->{start_regexp}'\n" if ($plan->{start_regexp});
  print "set starts at: " . join(', ', keys %{$plan->{start_lines}}) . "\n" if ($plan->{start_lines});
  print "\nstops\n";
  print "set stop   to '$plan->{stop_regexp}'\n" if ($plan->{stop_regexp});
  print "set stops  at: " . join(', ', keys %{$plan->{stop_lines}}) . "\n" if ($plan->{stop_lines});
  print "\nfiles?\n";
  print "$_\n" foreach (@{$plan->{files}});
  print "lead, linger: $plan->{lead}, $plan->{linger}\n";
  print "=" x 40 . "\n";
}

__END__
