#!/usr/bin/env perl
# A perl script to start on a given regexp and stop on another
# or a given line number and ending on another

use strict;
use warnings;

use Data::Dumper;
use Text::Abbrev;

my $last_mod_date='Wed, Jul 22, 2026';

my $version="1.2";

my $author="Dr. Steven Parker";
my $copyright="$last_mod_date. All rights reserved.";

my $name = $0; $name =~ s'.*/''; # remove path--like basename
my $usage  = "usage:\n$name\n\t";
$usage .= "[ ( -?      | --help  | --debug | --usage ) ]\n\t";
$usage .= "[ ( --on | --begin | --start | --start-after ) start_regexp ]\n\t";
$usage .= "[ ( --off | --end | --stop | --end-before ) stop_regexp ]\n\t";
$usage .= "[ ( --regexp | --find | --grep ) regexp ]\n\t";
$usage .= "[ --exclude-start ] [ --exclude-end ]\n\t";
$usage .= "[ --fixed ] [ --ignore-case ] [ --list-ranges ]\n\t";
$usage .= "[ --lead N --linger M | --context N ]\n\t";
$usage .= "[  N..M     |  N..   |  ..M  |  N  ]\n\t";
$usage .= "[ --number ]\n\t";
$usage .= "[ [ --file ] file1 file2 .. ]";

my $plan = initialize_plan();

parse_arguments($plan, @ARGV);
validate_plan($plan);
push @{$plan->{files}}, '-' unless @{$plan->{files}};
print Dumper($plan) if ($plan->{debug});
my $stats = execute_plan($plan);

exit 2 if $stats->{errors};
exit(
  $plan->{list_ranges}
    ? (@{$stats->{ranges}} ? 0 : 1)
    : ($stats->{lines_selected} ? 0 : 1)
);

sub initialize_plan {
  return {
    debug          => 0,
    end_patterns   => [],
    explanations   => [],
    files          => [],
    fixed           => 0,
    ignore_case     => 0,
    include_end     => 1,
    include_start   => 1,
    lead           => 0,
    linger         => 0,
    list_ranges    => 0,
    match_patterns => [],
    print_stops    => 1,
    ranges         => [],
    end_pattern_policies   => {},
    rules          => [],
    start_patterns => [],
    start_pattern_policies => {},
    start_lines    => {},
    start_printing => 0,
    stop_lines     => {},
  };
}

sub execute_plan {
  my $plan = shift;
  my $stats = {
    ends_matched        => 0,
    errors              => 0,
    files_processed     => 0,
    lines_printed       => 0,
    lines_read          => 0,
    lines_selected      => 0,
    lines_skipped       => 0,
    matches_by_rule     => {},
    ranges              => [],
    ranges_completed    => 0,
    ranges_unterminated => 0,
    starts_matched      => 0,
  };

  foreach my $file (@{$plan->{files}}) {
    my ($initial_rule) = grep { $_->{start_at_beginning} } @{$plan->{rules}};
    my $state = {
      active_range_start => $initial_rule
        ? ($initial_rule->{include_start} ? 1 : 2)
        : undef,
      active_rule        => $initial_rule,
      filename           => $file,
      lead_buffer        => [],
      line_number        => 0,
      linger_left        => 0,
    };

    my $filehandle;
    if ($file eq '-') {
      if (!open($filehandle, '<-')) {
        warn "Cannot read from STDIN: $!\n";
        $stats->{errors}++;
        next;
      }
    } else {
      if (!open($filehandle, '<', $file)) {
        warn "Cannot read from '$file': $!\n";
        $stats->{errors}++;
        next;
      }
    }
    $stats->{files_processed}++;

    while (my $line = <$filehandle>) {
      $state->{line_number}++;
      $stats->{lines_read}++;

      my $was_active = $state->{active_rule};
      my $rule = $was_active;
      my $implicit_start_event =
        $was_active
        && $was_active->{start_at_beginning}
        && $state->{line_number} == 1;
      my $start_event = $implicit_start_event;

      if (!$rule) {
        for my $candidate (@{$plan->{rules}}) {
          if (rule_start_matches($candidate, $line, $state->{line_number})) {
            $rule = $candidate;
            $start_event = 1;
            last;
          }
        }
      }

      my $end_match =
        $rule && rule_end_matches($rule, $line, $state->{line_number});
      my $single_match = $plan->{regexp} && $line =~ $plan->{regexp};
      my $active_end = $rule && $end_match;
      my $within_linger = $state->{linger_left} > 0;
      my $start_boundary_excluded =
        $start_event && !$rule->{include_start};
      my $end_boundary_excluded =
        $active_end && !$rule->{include_end};
      my $boundary_included =
        ($start_event && $rule->{include_start})
        || ($active_end && $rule->{include_end});
      my $range_interior =
        $was_active
        && !$start_boundary_excluded
        && !$end_boundary_excluded;
      my $context_selected =
        $within_linger
        && !$start_boundary_excluded
        && !$end_boundary_excluded;
      my $line_selected =
        $range_interior
        || $boundary_included
        || $single_match
        || $context_selected;

      if ($start_event) {
        $stats->{starts_matched}++;
        $stats->{matches_by_rule}{$rule->{name}}++;
      }
      $stats->{ends_matched}++ if $active_end;

      if ($start_event && !$implicit_start_event) {
        $state->{active_range_start} =
          $state->{line_number} + ($rule->{include_start} ? 0 : 1);
      }

      if ($single_match && !$plan->{has_range_conditions}) {
        record_range(
          $stats,
          $file,
          $state->{line_number},
          $state->{line_number},
          'match',
        );
      }

      if ($start_event || $single_match) {
        while (@{$state->{lead_buffer}}) {
          my $buffered = shift @{$state->{lead_buffer}};
          print_line(
            $plan,
            $state,
            $stats,
            $buffered->{text},
            $buffered->{number},
          );
        }
      }

      if ($line_selected) {
        print_line($plan, $state, $stats, $line);
      } else {
        if ($start_boundary_excluded || $end_boundary_excluded) {
          $stats->{lines_skipped}++;
        } elsif ($plan->{lead}) {
          push @{$state->{lead_buffer}}, {
            number => $state->{line_number},
            text   => $line,
          };
          if (@{$state->{lead_buffer}} > $plan->{lead}) {
            shift @{$state->{lead_buffer}};
            $stats->{lines_skipped}++;
          }
        } else {
          $stats->{lines_skipped}++;
        }
      }

      if ($active_end) {
        my ($selected_start, $selected_end);
        if ($start_event) {
          if ($rule->{include_start} || $rule->{include_end}) {
            $selected_start = $state->{line_number};
            $selected_end = $state->{line_number};
          }
        } else {
          $selected_start = $state->{active_range_start};
          $selected_end =
            $state->{line_number} - ($rule->{include_end} ? 0 : 1);
        }
        record_range(
          $stats,
          $file,
          $selected_start,
          $selected_end,
          $rule->{name},
        );
        $stats->{ranges_completed}++;
        $state->{active_range_start} = undef;
        $state->{active_rule} = undef;
      } elsif ($rule) {
        $state->{active_rule} = $rule;
      }

      $state->{linger_left}-- if $within_linger;
      if ($single_match || $active_end) {
        $state->{linger_left} = $plan->{linger}
          if $plan->{linger} > $state->{linger_left};
      }
    }

    if ($state->{active_rule}
        && $state->{line_number}
        && $state->{active_range_start} <= $state->{line_number}) {
      record_range(
        $stats,
        $file,
        $state->{active_range_start},
        'EOF',
        $state->{active_rule}{name},
      );
      $stats->{ranges_unterminated}++;
    }

    $stats->{lines_skipped} += @{$state->{lead_buffer}};
    if (!close($filehandle)) {
      warn "Cannot close '$file': $!\n";
      $stats->{errors}++;
    }
  }

  if ($plan->{list_ranges}) {
    for my $range (@{$stats->{ranges}}) {
      my $filename = $range->{file} eq '-' ? '<stdin>' : $range->{file};
      print join(
        "\t",
        $filename,
        $range->{start},
        $range->{end},
        $range->{rule},
      ), "\n";
    }
  }

  return $stats;
}

sub rule_start_matches {
  my ($rule, $line, $line_number) = @_;
  return
    ($rule->{start_lines} && $rule->{start_lines}{$line_number})
    || ($rule->{start_regexp} && $line =~ $rule->{start_regexp});
}

sub rule_end_matches {
  my ($rule, $line, $line_number) = @_;
  return
    ($rule->{stop_lines} && $rule->{stop_lines}{$line_number})
    || ($rule->{stop_regexp} && $line =~ $rule->{stop_regexp});
}

sub print_line {
  my ($plan, $state, $stats, $line, $line_number) = @_;
  $line_number //= $state->{line_number};
  $stats->{lines_selected}++;
  return if $plan->{list_ranges};
  $stats->{lines_printed}++;
  printf "%5d ", $line_number if ($plan->{number});
  print $line;
}

sub record_range {
  my ($stats, $file, $start, $end, $rule) = @_;
  return unless defined $start;
  return if $end ne 'EOF' && $start > $end;
  push @{$stats->{ranges}}, {
    end   => $end,
    file  => $file,
    rule  => $rule,
    start => $start,
  };
}

sub parse_arguments {
  my $plan = shift;
  my @options = qw(
    ? help debug usage
    regexp find grep
    on start begin start-after
    off stop end end-before
    number lead linger context file rule
    exclude-start exclude-end
    fixed ignore-case list-ranges
  );
  @options = map { "-$_" } @options;
  my $abbrev = abbrev @options;
  my @legacy_options = map { "-$_" } qw(
    ? help debug usage
    regexp find grep
    on start begin off stop end
    number lead linger context file
    fixed ignore-case list-ranges
  );
  my $legacy_abbrev = abbrev @legacy_options;
  $abbrev->{$_} = $legacy_abbrev->{$_} for keys %{$legacy_abbrev};
  my %takes_value = map { $_ => 1 } qw(
    -regexp -find -grep
    -on -start -begin -start-after
    -off -stop -end -end-before
    -lead -linger -context -file -rule
  );

  $plan->{explanations} = [
    { arg => '--help, -help, -?', explanation => 'print detailed help' },
    { arg => '--usage, -usage', explanation => 'print a short usage summary' },
    { arg => '--start, -start', explanation => 'regexp to trigger printing' },
    { arg => '--start-after', explanation => 'start after an excluded matching line' },
    { arg => '--end, -end', explanation => 'regexp to terminate printing' },
    { arg => '--end-before', explanation => 'stop before an excluded matching line' },
    { arg => '--regexp, -regexp', explanation => 'regexp selecting individual lines' },
    { arg => '--rule NAME', explanation => 'begin a named paired range rule' },
    { arg => '--exclude-start', explanation => 'exclude the starting boundary' },
    { arg => '--exclude-end', explanation => 'exclude the ending boundary' },
    { arg => '--fixed', explanation => 'treat expressions as literal strings' },
    { arg => '--ignore-case', explanation => 'match without regard to letter case' },
    { arg => '--lead N', explanation => 'print N lines before a trigger' },
    { arg => '--linger N', explanation => 'print N lines after a trigger' },
    { arg => '--context N', explanation => 'print N lines before and after a trigger' },
    { arg => '--number', explanation => 'prefix output with line numbers' },
    { arg => '--list-ranges', explanation => 'list matched ranges without their contents' },
    { arg => '--file FILE', explanation => 'add an input file' },
    { arg => '--debug', explanation => 'show parsing and processing details' },
    { arg => 'N | N.. | ..M | N..M', explanation => 'select numeric lines or ranges' },
  ];

  my $current_rule;

  while (@ARGV) {
    if ($ARGV[0] eq '--') {
      shift @ARGV;
      push @{$plan->{files}}, splice @ARGV;
      last;
    }

    my $raw_option = $ARGV[0];
    my $lookup = $raw_option;
    $lookup =~ s/^--/-/;
    my $option = $abbrev->{$lookup};

    if ($option) {
      shift @ARGV;
      usage_error("option '$raw_option' requires a value")
        if $takes_value{$option} && !@ARGV;
      my $value = $takes_value{$option} ? shift @ARGV : undef;

      if ($option eq '-help' || $option eq '-?') {
        help($plan);
      } elsif ($option eq '-usage') {
        print "$usage\n";
        exit 0;
      } elsif ($option eq '-debug') {
        $plan->{debug} = 1;
      } elsif ($option eq '-rule') {
        $current_rule = {
          end_pattern_policies   => {},
          end_patterns           => [],
          include_end            => $plan->{include_end},
          include_start          => $plan->{include_start},
          match_patterns         => [],
          name                   => $value,
          start_pattern_policies => {},
          start_patterns         => [],
        };
        push @{$plan->{rules}}, $current_rule;
      } elsif ($option eq '-number') {
        $plan->{number} = 1;
      } elsif ($option eq '-fixed') {
        $plan->{fixed} = 1;
      } elsif ($option eq '-ignore-case') {
        $plan->{ignore_case} = 1;
      } elsif ($option eq '-exclude-start') {
        if ($current_rule) {
          $current_rule->{include_start} = 0;
        } else {
          $plan->{include_start} = 0;
        }
      } elsif ($option eq '-exclude-end') {
        if ($current_rule) {
          $current_rule->{include_end} = 0;
        } else {
          $plan->{include_end} = 0;
        }
      } elsif ($option eq '-list-ranges') {
        $plan->{list_ranges} = 1;
      } elsif ($option =~ /^-(?:regexp|find|grep)$/) {
        push @{$plan->{match_patterns}}, $value;
      } elsif ($option =~ /^-(?:on|start|begin)$/) {
        my $owner = $current_rule || $plan;
        push @{$owner->{start_patterns}}, $value;
        $owner->{start_pattern_policies}{inclusive} = 1;
      } elsif ($option eq '-start-after') {
        my $owner = $current_rule || $plan;
        push @{$owner->{start_patterns}}, $value;
        $owner->{start_pattern_policies}{exclusive} = 1;
        $owner->{include_start} = 0;
      } elsif ($option =~ /^-(?:off|stop|end)$/) {
        my $owner = $current_rule || $plan;
        push @{$owner->{end_patterns}}, $value;
        $owner->{end_pattern_policies}{inclusive} = 1;
      } elsif ($option eq '-end-before') {
        my $owner = $current_rule || $plan;
        push @{$owner->{end_patterns}}, $value;
        $owner->{end_pattern_policies}{exclusive} = 1;
        $owner->{include_end} = 0;
      } elsif ($option eq '-lead') {
        validate_nonnegative_integer('--lead', $value);
        $plan->{lead} = $value;
      } elsif ($option eq '-linger') {
        validate_nonnegative_integer('--linger', $value);
        $plan->{linger} = $value;
      } elsif ($option eq '-context') {
        validate_nonnegative_integer('--context', $value);
        $plan->{lead} = $value;
        $plan->{linger} = $value;
      } elsif ($option eq '-file') {
        push @{$plan->{files}}, $value;
      }
      next;
    }

    my $argument = shift @ARGV;
    if ($argument =~ m'^-?(\d+)\.\.(\d+)$') {                                    # N to M
      usage_error('line numbers must be greater than zero') if $1 == 0 || $2 == 0;
      usage_error("range start $1 is greater than range end $2") if $1 > $2;
      $plan->{start_lines}{$1}++;
      $plan->{stop_lines}{$2}++;
      print "user has requested printing of lines $1 to $2 inclusive\n" if ($plan->{debug});
    } elsif ($argument =~ m'^-?(\d+)\.\.$') {                                          # N on
      usage_error('line numbers must be greater than zero') if $1 == 0;
      $plan->{start_lines}{$1}++;
      print "user has requested printing of lines starting at $1\n" if ($plan->{debug});
    } elsif ($argument =~ m'^-?\.\.(\d+)$') {                                          #   to M
      usage_error('line numbers must be greater than zero') if $1 == 0;
      $plan->{start_printing} = 1;
      $plan->{stop_lines}{$1}++;
      push( @{$plan->{ranges}}, { start=>undef, end=>$1 } );
      print "user has requested printing of lines up to $1\n" if ($plan->{debug});
    } elsif ($argument =~ m'^-?(\d+)$') {                                              # just print line N
      usage_error('line numbers must be greater than zero') if $1 == 0;
      $plan->{start_lines}{$1}++;
      $plan->{stop_lines}{$1}++;
      print "user has requested printing of line $1\n" if ($plan->{debug});
    } elsif ($argument =~ m'^-?([^.]*)\.\.([^.]*)$') {                                # START to STOP
      my $front=$1;
      my $back=$2;
      if ($front eq '' and $back eq '') {
        usage_error("'..' is not a valid range");
      } elsif ($front eq '') { # ..SOMETHING (not a number)
        print " ..X '$front' '$back'\n" if ($plan->{debug});
        $plan->{start_printing} = 1;
        push @{$plan->{end_patterns}}, $back;
      } elsif ($back eq '') { # SOMETHING.. (not a number)
        print "X..  '$front' '$back'\n" if ($plan->{debug});
        push @{$plan->{start_patterns}}, $front;
      } else {                # SOMETHING..SOMETHING_ELSE (at least one of which is not a number)
        print "X..Y '$front' '$back'\n" if ($plan->{debug});
        if ( $front=~/^\d+$/ ) {
          usage_error('line numbers must be greater than zero') if $front == 0;
          print "N..? '$front' '$back'\n" if ($plan->{debug});
          $plan->{start_lines}{$front}++;
        } else {
          print "X..? '$front' '$back'\n" if ($plan->{debug});
          push @{$plan->{start_patterns}}, $front;
        }
        if ( $back=~/^\d+$/ ) {
          usage_error('line numbers must be greater than zero') if $back == 0;
          print "?..N '$front' '$back'\n" if ($plan->{debug});
          $plan->{stop_lines}{$back}++;
        } else {
          print "?..X '$front' '$back'\n" if ($plan->{debug});
          push @{$plan->{end_patterns}}, $back;
        }
      }
    } else {
      usage_error("unknown option '$argument'")
        if $argument =~ /^-/ && $argument ne '-';
      push @{$plan->{files}}, $argument;
    }
  }

  compile_plan_patterns($plan);

  if ($plan->{debug}) {
    report_plan($plan);
  }
}

sub validate_plan {
  my $plan = shift;
  validate_nonnegative_integer('--lead', $plan->{lead});
  validate_nonnegative_integer('--linger', $plan->{linger});

  my $standard_inputs = grep { $_ eq '-' } @{$plan->{files}};
  usage_error("standard input '-' may only be specified once")
    if $standard_inputs > 1;

  usage_error('mixed start boundary policies require explicit paired rules')
    if keys %{$plan->{start_pattern_policies}} > 1;
  usage_error('mixed end boundary policies require explicit paired rules')
    if keys %{$plan->{end_pattern_policies}} > 1;

  my $has_implicit_range =
    $plan->{start_printing}
    || keys %{$plan->{start_lines}}
    || keys %{$plan->{stop_lines}}
    || @{$plan->{start_patterns}}
    || @{$plan->{end_patterns}};

  my $has_explicit_rules = @{$plan->{rules}} > 0;
  usage_error('cannot mix explicit rules with implicit ranges')
    if $has_explicit_rules && $has_implicit_range;

  if ($has_explicit_rules) {
    my %rule_names;
    for my $rule (@{$plan->{rules}}) {
      usage_error("invalid rule name '$rule->{name}'")
        unless defined $rule->{name}
          && $rule->{name} =~ /^[A-Za-z][A-Za-z0-9_-]*$/;
      usage_error("duplicate rule name '$rule->{name}'")
        if $rule_names{$rule->{name}}++;
      usage_error("rule '$rule->{name}' requires at least one start")
        unless @{$rule->{start_patterns}};
      usage_error("rule '$rule->{name}' requires at least one end")
        unless @{$rule->{end_patterns}};
      usage_error("mixed start boundary policies in rule '$rule->{name}'")
        if keys %{$rule->{start_pattern_policies}} > 1;
      usage_error("mixed end boundary policies in rule '$rule->{name}'")
        if keys %{$rule->{end_pattern_policies}} > 1;
    }
  } elsif ($has_implicit_range) {
    push @{$plan->{rules}}, {
      end_patterns   => $plan->{end_patterns},
      include_end    => $plan->{include_end},
      include_start  => $plan->{include_start},
      name           => 'default',
      start_at_beginning => $plan->{start_printing},
      start_lines    => $plan->{start_lines},
      start_patterns => $plan->{start_patterns},
      start_regexp   => $plan->{start_regexp},
      stop_lines     => $plan->{stop_lines},
      stop_regexp    => $plan->{stop_regexp},
    };
  }

  $plan->{has_range_conditions} = @{$plan->{rules}} > 0;
}

sub validate_nonnegative_integer {
  my ($option, $value) = @_;
  usage_error("$option requires a non-negative integer")
    unless defined $value && $value =~ /^\d+$/;
}

sub compile_plan_patterns {
  my $plan = shift;
  compile_pattern_owner($plan, $plan);
  compile_pattern_owner($plan, $_) for @{$plan->{rules}};
}

sub compile_pattern_owner {
  my ($plan, $owner) = @_;
  for my $specification (
    ['start', 'start_patterns', 'start_regexp'],
    ['end',   'end_patterns',   'stop_regexp'],
    ['match', 'match_patterns', 'regexp'],
  ) {
    my ($kind, $patterns_key, $regexp_key) = @{$specification};
    next unless @{$owner->{$patterns_key}};

    my @patterns;
    for my $source (@{$owner->{$patterns_key}}) {
      my $prepared = $plan->{fixed} ? quotemeta($source) : $source;
      compile_regexp($kind, $prepared, $plan->{ignore_case});
      push @patterns, "(?:$prepared)";
    }
    $owner->{$regexp_key} = compile_regexp(
      $kind,
      join('|', @patterns),
      $plan->{ignore_case},
    );
  }
}

sub compile_regexp {
  my ($kind, $source, $ignore_case) = @_;
  my $regexp = eval {
    $ignore_case ? qr/$source/i : qr/$source/
  };
  if (!$regexp || $@) {
    my $error = $@ || 'unknown regular-expression error';
    $error =~ s/\s+at\s+\Q$0\E\s+line\s+\d+.*//s;
    chomp $error;
    usage_error("invalid $kind regular expression '$source': $error");
  }
  return $regexp;
}

sub usage_error {
  my $message = shift;
  warn "onoff: $message\n";
  exit 2;
}

sub help {
  my ($plan,@args) = @_;
  select(STDOUT); $|=1; $\=''; 
  if (@{$plan->{explanations}}) {
    foreach my $explanation ( @{$plan->{explanations}} ) {
      printf "%-16s\t%s\n", $explanation->{arg}, $explanation->{explanation};
    }
  } else {
    for (my $arg=$[; $arg<=$#args; $arg++) {
      print "$args[$arg]\t";
    }
    print "\n";
  }
  exit 0;
}

sub report_plan {
  my $plan = shift;
  print "singles\n";
  print "set regexp to '$plan->{regexp}'\n" if ($plan->{regexp});
  print "starts\n";
  print "set start  to '$plan->{start_regexp}'\n" if ($plan->{start_regexp});
  print "set starts at: " . join(', ', keys %{$plan->{start_lines}}) . "\n" if ($plan->{start_lines});
  print "\nstops\n";
  print "set stop   to '$plan->{stop_regexp}'\n" if ($plan->{stop_regexp});
  print "set stops  at: " . join(', ', keys %{$plan->{stop_lines}}) . "\n" if ($plan->{stop_lines});
  print "include start/end: $plan->{include_start}, $plan->{include_end}\n";
  if (@{$plan->{rules}}) {
    print "\nrules\n";
    for my $rule (@{$plan->{rules}}) {
      print "$rule->{name}: start '$rule->{start_regexp}', ";
      print "end '$rule->{stop_regexp}', ";
      print "include $rule->{include_start}/$rule->{include_end}\n";
    }
  }
  print "\nfiles?\n";
  print "$_\n" foreach (@{$plan->{files}});
  print "lead, linger: $plan->{lead}, $plan->{linger}\n";
  print "=" x 40 . "\n";
}

__END__
